default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  port: 5432

development:
  <<: *default
  database: real_state_prototype_api_development

test:
  <<: *default
  database: real_state_prototype_api_test

production:
  <<: *default
  database: real_state_prototype_api_production
  username: real_state_prototype_api
  password: <%= ENV['REAL_STATE_PROTOTYPE_API_DATABASE_PASSWORD'] %>
